### ISSUE TITLE
Practica 4

### ISSUE THREAD

**Issue by edgarmauricio123** [SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-en-web-3-0-equipo-1-1#1]
[MODELO DE NEGOCIOS.pdf](https://github.com/user-attachments/files/17121081/MODELO.DE.NEGOCIOS.pdf)

**Comment by AmeliReyesHernandez** [comment]
20 de 20 cumple con todos los requisitos de la rubrica :)

**Comment by josealfredo79** [comment]
bien hecho y revisado...
