### ISSUE TITLE
practica 6 

### ISSUE THREAD

**Issue by ErikCuevas03** [SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-en-web-3-0-equipo-1-1#2]
[practica 3 software 2.pdf](https://github.com/user-attachments/files/17122370/practica.3.software.2.pdf)

**Comment by Vanessacruzortiz** [comment]
Calificación 20 de 20 cumple con los requisitos de acuerdo a la rubrica .

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
